version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: google.golang.org/grpc
    versions:
    - 1.35.0
    - 1.36.0
    - 1.36.1
  - dependency-name: github.com/golang/protobuf
    versions:
    - 1.5.1
  - dependency-name: github.com/spf13/cobra
    versions:
    - 1.1.1
    - 1.1.2
  - dependency-name: github.com/google/trillian
    versions:
    - 1.3.11
  - dependency-name: github.com/go-openapi/swag
    versions:
    - 0.19.14
  - dependency-name: github.com/google/go-cmp
    versions:
    - 0.5.4
  - dependency-name: github.com/go-openapi/spec
    versions:
    - 0.20.2
